/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaMediaIdStatusPostRequest {
    /// When true, updates the 4K status field (status4k). When false or not provided, updates the regular status field (status). This applies to all status values (available, partial, processing, pending, unknown).
    #[serde(rename = "is4k", skip_serializing_if = "Option::is_none")]
    pub is4k: Option<bool>,
}

impl MediaMediaIdStatusPostRequest {
    pub fn new() -> MediaMediaIdStatusPostRequest {
        MediaMediaIdStatusPostRequest { is4k: None }
    }
}
