/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaMediaIdWatchDataGet200ResponseData {
    #[serde(rename = "playCount7Days", skip_serializing_if = "Option::is_none")]
    pub play_count7_days: Option<f64>,
    #[serde(rename = "playCount30Days", skip_serializing_if = "Option::is_none")]
    pub play_count30_days: Option<f64>,
    #[serde(rename = "playCount", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<f64>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::User>>,
}

impl MediaMediaIdWatchDataGet200ResponseData {
    pub fn new() -> MediaMediaIdWatchDataGet200ResponseData {
        MediaMediaIdWatchDataGet200ResponseData {
            play_count7_days: None,
            play_count30_days: None,
            play_count: None,
            users: None,
        }
    }
}
