/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsSonarrTestPostRequest {
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "port")]
    pub port: f64,
    #[serde(rename = "apiKey")]
    pub api_key: String,
    #[serde(rename = "useSsl")]
    pub use_ssl: bool,
    #[serde(rename = "baseUrl", skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
}

impl SettingsSonarrTestPostRequest {
    pub fn new(
        hostname: String,
        port: f64,
        api_key: String,
        use_ssl: bool,
    ) -> SettingsSonarrTestPostRequest {
        SettingsSonarrTestPostRequest {
            hostname,
            port,
            api_key,
            use_ssl,
            base_url: None,
        }
    }
}
