/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsCacheGet200ResponseDnsCacheStats {
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    #[serde(rename = "maxSize", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<f64>,
    #[serde(rename = "hits", skip_serializing_if = "Option::is_none")]
    pub hits: Option<f64>,
    #[serde(rename = "misses", skip_serializing_if = "Option::is_none")]
    pub misses: Option<f64>,
    #[serde(rename = "failures", skip_serializing_if = "Option::is_none")]
    pub failures: Option<f64>,
    #[serde(rename = "ipv4Fallbacks", skip_serializing_if = "Option::is_none")]
    pub ipv4_fallbacks: Option<f64>,
    #[serde(rename = "hitRate", skip_serializing_if = "Option::is_none")]
    pub hit_rate: Option<f64>,
}

impl SettingsCacheGet200ResponseDnsCacheStats {
    pub fn new() -> SettingsCacheGet200ResponseDnsCacheStats {
        SettingsCacheGet200ResponseDnsCacheStats {
            size: None,
            max_size: None,
            hits: None,
            misses: None,
            failures: None,
            ipv4_fallbacks: None,
            hit_rate: None,
        }
    }
}
