/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserUserIdWatchDataGet200Response {
    #[serde(rename = "recentlyWatched", skip_serializing_if = "Option::is_none")]
    pub recently_watched: Option<Vec<models::MediaInfo>>,
    #[serde(rename = "playCount", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<f64>,
}

impl UserUserIdWatchDataGet200Response {
    pub fn new() -> UserUserIdWatchDataGet200Response {
        UserUserIdWatchDataGet200Response {
            recently_watched: None,
            play_count: None,
        }
    }
}
