/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserImportFromPlexPostRequest {
    #[serde(rename = "plexIds", skip_serializing_if = "Option::is_none")]
    pub plex_ids: Option<Vec<String>>,
}

impl UserImportFromPlexPostRequest {
    pub fn new() -> UserImportFromPlexPostRequest {
        UserImportFromPlexPostRequest { plex_ids: None }
    }
}
