/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscordSettingsOptions {
    #[serde(rename = "botUsername", skip_serializing_if = "Option::is_none")]
    pub bot_username: Option<String>,
    #[serde(rename = "botAvatarUrl", skip_serializing_if = "Option::is_none")]
    pub bot_avatar_url: Option<String>,
    #[serde(rename = "webhookUrl", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
    #[serde(rename = "webhookRoleId", skip_serializing_if = "Option::is_none")]
    pub webhook_role_id: Option<String>,
    #[serde(rename = "enableMentions", skip_serializing_if = "Option::is_none")]
    pub enable_mentions: Option<bool>,
}

impl DiscordSettingsOptions {
    pub fn new() -> DiscordSettingsOptions {
        DiscordSettingsOptions {
            bot_username: None,
            bot_avatar_url: None,
            webhook_url: None,
            webhook_role_id: None,
            enable_mentions: None,
        }
    }
}
