/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaRequest {
    #[serde(rename = "id")]
    pub id: f64,
    /// Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
    #[serde(rename = "status")]
    pub status: f64,
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<Box<models::MediaInfo>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "requestedBy", skip_serializing_if = "Option::is_none")]
    pub requested_by: Option<Box<models::User>>,
    #[serde(rename = "modifiedBy", skip_serializing_if = "Option::is_none")]
    pub modified_by: Option<Box<models::MediaRequestModifiedBy>>,
    #[serde(rename = "is4k", skip_serializing_if = "Option::is_none")]
    pub is4k: Option<bool>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<f64>,
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<f64>,
    #[serde(rename = "rootFolder", skip_serializing_if = "Option::is_none")]
    pub root_folder: Option<String>,
}

impl MediaRequest {
    pub fn new(id: f64, status: f64) -> MediaRequest {
        MediaRequest {
            id,
            status,
            media: None,
            created_at: None,
            updated_at: None,
            requested_by: None,
            modified_by: None,
            is4k: None,
            server_id: None,
            profile_id: None,
            root_folder: None,
        }
    }
}
