/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataSettingsSettings {
    #[serde(rename = "tv", skip_serializing_if = "Option::is_none")]
    pub tv: Option<Tv>,
    #[serde(rename = "anime", skip_serializing_if = "Option::is_none")]
    pub anime: Option<Anime>,
}

impl MetadataSettingsSettings {
    pub fn new() -> MetadataSettingsSettings {
        MetadataSettingsSettings {
            tv: None,
            anime: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tv {
    #[serde(rename = "tvdb")]
    Tvdb,
    #[serde(rename = "tmdb")]
    Tmdb,
}

impl Default for Tv {
    fn default() -> Tv {
        Self::Tvdb
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Anime {
    #[serde(rename = "tvdb")]
    Tvdb,
    #[serde(rename = "tmdb")]
    Tmdb,
}

impl Default for Anime {
    fn default() -> Anime {
        Self::Tvdb
    }
}
