/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkSettings {
    #[serde(rename = "csrfProtection", skip_serializing_if = "Option::is_none")]
    pub csrf_protection: Option<bool>,
    #[serde(rename = "forceIpv4First", skip_serializing_if = "Option::is_none")]
    pub force_ipv4_first: Option<bool>,
    #[serde(rename = "trustProxy", skip_serializing_if = "Option::is_none")]
    pub trust_proxy: Option<bool>,
    #[serde(rename = "proxy", skip_serializing_if = "Option::is_none")]
    pub proxy: Option<Box<models::NetworkSettingsProxy>>,
    #[serde(rename = "dnsCache", skip_serializing_if = "Option::is_none")]
    pub dns_cache: Option<Box<models::NetworkSettingsDnsCache>>,
}

impl NetworkSettings {
    pub fn new() -> NetworkSettings {
        NetworkSettings {
            csrf_protection: None,
            force_ipv4_first: None,
            trust_proxy: None,
            proxy: None,
            dns_cache: None,
        }
    }
}
