/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageInfo {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    #[serde(rename = "pages", skip_serializing_if = "Option::is_none")]
    pub pages: Option<f64>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<f64>,
}

impl PageInfo {
    pub fn new() -> PageInfo {
        PageInfo {
            page: None,
            pages: None,
            results: None,
        }
    }
}
