/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SonarrSeriesAddOptionsInner {
    #[serde(
        rename = "ignoreEpisodesWithFiles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_episodes_with_files: Option<Option<bool>>,
    #[serde(
        rename = "ignoreEpisodesWithoutFiles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_episodes_without_files: Option<Option<bool>>,
    #[serde(
        rename = "searchForMissingEpisodes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub search_for_missing_episodes: Option<Option<bool>>,
}

impl SonarrSeriesAddOptionsInner {
    pub fn new() -> SonarrSeriesAddOptionsInner {
        SonarrSeriesAddOptionsInner {
            ignore_episodes_with_files: None,
            ignore_episodes_without_files: None,
            search_for_missing_episodes: None,
        }
    }
}
