/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TelegramSettingsOptions {
    #[serde(rename = "botUsername", skip_serializing_if = "Option::is_none")]
    pub bot_username: Option<String>,
    #[serde(rename = "botAPI", skip_serializing_if = "Option::is_none")]
    pub bot_api: Option<String>,
    #[serde(rename = "chatId", skip_serializing_if = "Option::is_none")]
    pub chat_id: Option<String>,
    #[serde(rename = "messageThreadId", skip_serializing_if = "Option::is_none")]
    pub message_thread_id: Option<String>,
    #[serde(rename = "sendSilently", skip_serializing_if = "Option::is_none")]
    pub send_silently: Option<bool>,
}

impl TelegramSettingsOptions {
    pub fn new() -> TelegramSettingsOptions {
        TelegramSettingsOptions {
            bot_username: None,
            bot_api: None,
            chat_id: None,
            message_thread_id: None,
            send_silently: None,
        }
    }
}
