services:
    doplarr:
        image: ghcr.io/activexray/doplarr_rs:latest
        container_name: doplarr
        restart: unless-stopped
        volumes:
            - ./config.toml:/config.toml:ro
