{
  description = "Nix flake for Doplarr (Rust)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    crane.url = "github:ipetkov/crane";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    advisory-db = {
      url = "github:rustsec/advisory-db";
      flake = false;
    };
  };

  outputs = {
    self,
    nixpkgs,
    crane,
    flake-utils,
    rust-overlay,
    advisory-db,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (
      system: let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [(import rust-overlay)];
        };

        inherit (pkgs) lib;

        craneLib = (crane.mkLib pkgs).overrideToolchain (
          p:
            p.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml
        );

        src = craneLib.cleanCargoSource ./.;

        # The build sandbox has no `.git`, so hand the binary's build.rs the
        # flake's own revision. `shortRev` is present for a clean tree, and
        # `dirtyShortRev` for a working tree with uncommitted changes; both are
        # absent (falling back to "unknown") when built from a tarball with no
        # git metadata. Passed only to the final binaries below - not to
        # buildDepsOnly - so the dependency cache survives across commits.
        gitRev = self.shortRev or self.dirtyShortRev or "unknown";

        commonArgs = {
          inherit src;
          strictDeps = true;
          nativeBuildInputs = with pkgs;
            [cmake]
            ++ lib.optionals stdenv.isx86_64 [nasm]
            ++ lib.optionals stdenv.isDarwin [libiconv];
          buildInputs = [];
        };

        cargoArtifacts = craneLib.buildDepsOnly commonArgs;

        doplarr = craneLib.buildPackage (
          commonArgs
          // {
            pname = "doplarr";
            cargoExtraArgs = "-p doplarr";
            GIT_HASH = gitRev;
          }
        );

        # Static musl binary (Linux x86_64 only)
        muslPkgs = pkgs.pkgsCross.musl64;
        muslCC = "${muslPkgs.stdenv.cc}/bin/${muslPkgs.stdenv.cc.targetPrefix}cc";
        muslAR = "${muslPkgs.stdenv.cc}/bin/${muslPkgs.stdenv.cc.targetPrefix}ar";

        commonArgsMusl = commonArgs // {
          CARGO_BUILD_TARGET = "x86_64-unknown-linux-musl";
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static";
          "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER" = muslCC;
          "CC_x86_64_unknown_linux_musl" = muslCC;
          "AR_x86_64_unknown_linux_musl" = muslAR;
          nativeBuildInputs = commonArgs.nativeBuildInputs ++ [muslPkgs.stdenv.cc];
          doCheck = false;
        };

        cargoArtifactsMusl = craneLib.buildDepsOnly commonArgsMusl;

        doplarrStatic = craneLib.buildPackage (commonArgsMusl // {
          cargoArtifacts = cargoArtifactsMusl;
          pname = "doplarr";
          cargoExtraArgs = "-p doplarr";
          GIT_HASH = gitRev;
        });

        # Static musl binary — aarch64
        aarch64MuslPkgs = pkgs.pkgsCross.aarch64-multiplatform-musl;
        aarch64CC = "${aarch64MuslPkgs.stdenv.cc}/bin/${aarch64MuslPkgs.stdenv.cc.targetPrefix}cc";
        aarch64AR = "${aarch64MuslPkgs.stdenv.cc}/bin/${aarch64MuslPkgs.stdenv.cc.targetPrefix}ar";

        commonArgsAarch64Musl = commonArgs // {
          CARGO_BUILD_TARGET = "aarch64-unknown-linux-musl";
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static";
          "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER" = aarch64CC;
          "CC_aarch64_unknown_linux_musl" = aarch64CC;
          "AR_aarch64_unknown_linux_musl" = aarch64AR;
          nativeBuildInputs = commonArgs.nativeBuildInputs ++ [aarch64MuslPkgs.stdenv.cc];
          doCheck = false;
        };

        cargoArtifactsAarch64Musl = craneLib.buildDepsOnly commonArgsAarch64Musl;

        doplarrStaticAarch64 = craneLib.buildPackage (commonArgsAarch64Musl // {
          cargoArtifacts = cargoArtifactsAarch64Musl;
          pname = "doplarr";
          cargoExtraArgs = "-p doplarr";
          GIT_HASH = gitRev;
        });

        # Clippy as SARIF, compiled once. crane runs clippy and emits a SARIF
        # report GitHub can render as inline annotations. It always succeeds so
        # the report is produced even when there are findings; the `clippy`
        # check below turns any finding into a failure (preserving the old
        # `--deny warnings` behaviour). We skip the api crates (autogenerated).
        clippySarif = craneLib.mkCargoDerivation (commonArgs
          // {
            inherit cargoArtifacts;
            pnameSuffix = "-clippy-sarif";
            # It's a report, not a build - no need to cache the target dir.
            doInstallCargoArtifacts = false;
            nativeBuildInputs = commonArgs.nativeBuildInputs ++ [pkgs.clippy-sarif];
            # `cargoWithProfile` + `--locked` mirror crane's own cargoClippy. The
            # `|| true` keeps the derivation green so the SARIF is always
            # produced; findings are gated by `clippyCheck` below.
            buildPhaseCargoCommand = ''
              cargoWithProfile clippy --locked -p doplarr --all-targets \
                --message-format=json -- --no-deps > clippy.json || true
              clippy-sarif < clippy.json > clippy.sarif
              # Make file URIs repo-relative (strip the sandbox build dir) so the
              # GitHub checkout resolves them to real files.
              sed -i "s#$PWD/##g" clippy.sarif
            '';
            installPhaseCommand = ''
              mkdir -p $out
              cp clippy.sarif $out/clippy.sarif
            '';
          });

        # No-compile gate: fail if the SARIF above has any findings.
        clippyCheck = pkgs.runCommand "doplarr-clippy" {nativeBuildInputs = [pkgs.jq pkgs.sarif-fmt];} ''
          report=${clippySarif}/clippy.sarif
          count=$(jq '[.runs[].results[]] | length' "$report")
          if [ "$count" -ne 0 ]; then
            echo "clippy reported $count finding(s):"
            sarif-fmt < "$report" || cat "$report"
            exit 1
          fi
          echo "clippy: clean"
          touch $out
        '';
      in {
        checks = {
          # Build the crates as part of `nix flake check` for convenience
          inherit doplarr;

          # Clippy gate (reads the SARIF report; see clippySarif above).
          clippy = clippyCheck;

          # Check formatting
          fmt = craneLib.cargoFmt {
            inherit src;
          };

          toml-fmt = craneLib.taploFmt {
            src = pkgs.lib.sources.sourceFilesBySuffices src [".toml"];
            # taplo arguments can be further customized below as needed
            # taploExtraArgs = "--config ./taplo.toml";
          };

          # Audit dependencies
          audit = craneLib.cargoAudit {
            inherit src advisory-db;
          };
        };

        packages =
          {
            default = doplarr;
            # The clippy SARIF report, for CI to upload as code-scanning results.
            clippy-sarif = clippySarif;
          }
          // lib.optionalAttrs pkgs.stdenv.isLinux {
            static = doplarrStatic;
            staticAarch64 = doplarrStaticAarch64;

            dockerImage = pkgs.dockerTools.buildLayeredImage {
              name = "ghcr.io/activexray/doplarr_rs";
              tag = "latest";
              contents = [doplarrStatic pkgs.cacert];
              config = {
                Cmd = ["${doplarrStatic}/bin/doplarr"];
                ExposedPorts = {};
                Env = [
                  "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
                ];
              };
            };

            dockerImageAarch64 = pkgs.dockerTools.buildLayeredImage {
              name = "ghcr.io/activexray/doplarr_rs";
              tag = "latest";
              architecture = "arm64";
              contents = [doplarrStaticAarch64 pkgs.cacert];
              config = {
                Cmd = ["${doplarrStaticAarch64}/bin/doplarr"];
                ExposedPorts = {};
                Env = [
                  "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
                ];
              };
            };

          };

        apps.default = flake-utils.lib.mkApp {
          drv = doplarr;
        };

        devShells.default = craneLib.devShell {
          # Inherit inputs from checks.
          checks = self.checks.${system};

          # Additional dev-shell environment variables can be set directly
          # MY_CUSTOM_DEVELOPMENT_VAR = "something else";

          # Extra inputs can be added here; cargo and rustc are provided by default.
          packages = with pkgs; [
            openapi-generator-cli
            cargo-outdated
          ];
        };
      }
    );
}
