/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiInfoResource {
    #[serde(
        rename = "current",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current: Option<Option<String>>,
    #[serde(
        rename = "deprecated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub deprecated: Option<Option<Vec<String>>>,
}

impl ApiInfoResource {
    pub fn new() -> ApiInfoResource {
        ApiInfoResource {
            current: None,
            deprecated: None,
        }
    }
}
