/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(
        rename = "personName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub person_name: Option<Option<String>>,
    #[serde(
        rename = "creditTmdbId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credit_tmdb_id: Option<Option<String>>,
    #[serde(rename = "personTmdbId", skip_serializing_if = "Option::is_none")]
    pub person_tmdb_id: Option<i32>,
    #[serde(rename = "movieMetadataId", skip_serializing_if = "Option::is_none")]
    pub movie_metadata_id: Option<i32>,
    #[serde(
        rename = "images",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub images: Option<Option<Vec<models::MediaCover>>>,
    #[serde(
        rename = "department",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub department: Option<Option<String>>,
    #[serde(
        rename = "job",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub job: Option<Option<String>>,
    #[serde(
        rename = "character",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub character: Option<Option<String>>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::CreditType>,
}

impl CreditResource {
    pub fn new() -> CreditResource {
        CreditResource {
            id: None,
            person_name: None,
            credit_tmdb_id: None,
            person_tmdb_id: None,
            movie_metadata_id: None,
            images: None,
            department: None,
            job: None,
            character: None,
            order: None,
            r#type: None,
        }
    }
}
