/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportListBulkResource {
    #[serde(
        rename = "ids",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ids: Option<Option<Vec<i32>>>,
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<Vec<i32>>>,
    #[serde(rename = "applyTags", skip_serializing_if = "Option::is_none")]
    pub apply_tags: Option<models::ApplyTags>,
    #[serde(
        rename = "enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enabled: Option<Option<bool>>,
    #[serde(
        rename = "enableAuto",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_auto: Option<Option<bool>>,
    #[serde(
        rename = "rootFolderPath",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub root_folder_path: Option<Option<String>>,
    #[serde(
        rename = "qualityProfileId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub quality_profile_id: Option<Option<i32>>,
    #[serde(
        rename = "minimumAvailability",
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_availability: Option<models::MovieStatusType>,
}

impl ImportListBulkResource {
    pub fn new() -> ImportListBulkResource {
        ImportListBulkResource {
            ids: None,
            tags: None,
            apply_tags: None,
            enabled: None,
            enable_auto: None,
            root_folder_path: None,
            quality_profile_id: None,
            minimum_availability: None,
        }
    }
}
